version: "3.9"
services:
  api:
    container_name: flask-container
    build: .
    image: kaneai/flask-heroku:v1
    env_file:
      - .env
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
